# Generated by Django 3.1.7 on 2021-03-27 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='category',
            field=models.CharField(choices=[('PR', 'PREMIUM ROOM'), ('SU', 'SUPERIOR ROOM'), ('SR', 'SUITE ROOM'), ('HS', 'HILL VIEW SUITE'), ('PS', 'PRESIDENTIAL SUITE')], max_length=3),
        ),
    ]
