# Generated by Django 3.1.7 on 2021-08-30 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0011_auto_20210830_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='category',
            field=models.CharField(choices=[('PR', 'PREMIUM ROOM'), ('SU', 'SUPERIOR ROOM'), ('SR', 'SUITE ROOM'), ('HS', 'HILL VIEW SUITE'), ('PS', 'PRESIDENTIAL SUITE')], max_length=3),
        ),
    ]
